import re
from youtube_transcript_api import YouTubeTranscriptApi
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_classic.chains import create_retrieval_chain

def extract_video_id(url_or_id):
    """
    Extracts the 11-character YouTube video ID from a URL or raw ID string.
    """
    url_or_id = url_or_id.strip()
    
    # Common YouTube URL patterns
    patterns = [
        r'(?:https?://)?(?:www\.|m\.)?youtube\.com/watch\?(?:[^&]*&)*v=([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?(?:www\.)?youtu\.be/([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?(?:www\.|m\.)?youtube\.com/embed/([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?(?:www\.|m\.)?youtube\.com/v/([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?(?:www\.|m\.)?youtube\.com/shorts/([a-zA-Z0-9_-]{11})',
        r'(?:https?://)?(?:www\.|m\.)?youtube\.com/live/([a-zA-Z0-9_-]{11})',
        r'^([a-zA-Z0-9_-]{11})$'  # Raw ID
    ]
    
    for pattern in patterns:
        match = re.search(pattern, url_or_id)
        if match:
            return match.group(1)
    
    return None

def fetch_transcript_text(video_id):
    """
    Fetches the transcript text for a given YouTube video ID.
    Tries English first, falls back to any other available language.
    """
    try:
        transcript_list = YouTubeTranscriptApi().list(video_id)
        
        # Try to find English transcript (preferred)
        try:
            transcript = transcript_list.find_transcript(['en'])
        except Exception:
            # Fall back to any available transcript (e.g. autogenerated, translation)
            transcript = next(iter(transcript_list))
            
        data = transcript.fetch()
        
        # Combine text segments
        full_text = " ".join([entry.text for entry in data])
        return full_text
    except Exception as e:
        raise ValueError(f"Could not retrieve transcript for YouTube video {video_id}: {str(e)}")

import os
import streamlit as st

@st.cache_resource
def get_embeddings():
    """
    Loads and caches the HuggingFace embeddings model using Streamlit's cache.
    Uses GPU if available.
    """
    try:
        import torch
        device = "cuda" if torch.cuda.is_available() else "cpu"
    except ImportError:
        device = "cpu"
    return HuggingFaceEmbeddings(
        model_name="all-MiniLM-L6-v2",
        model_kwargs={"device": device}
    )

def has_cached_index(video_id):
    """
    Checks if a local FAISS index exists for the given video ID.
    """
    index_path = f"faiss_indexes/index_{video_id}"
    return (
        os.path.exists(os.path.join(index_path, "index.faiss")) and
        os.path.exists(os.path.join(index_path, "transcript.txt"))
    )

def load_cached_vector_store(video_id):
    """
    Loads a cached FAISS index from disk.
    """
    index_path = f"faiss_indexes/index_{video_id}"
    embeddings = get_embeddings()
    return FAISS.load_local(index_path, embeddings, allow_dangerous_deserialization=True)

def load_cached_transcript(video_id):
    """
    Loads raw transcript text from disk cache.
    """
    path = f"faiss_indexes/index_{video_id}/transcript.txt"
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    return ""

def create_vector_store(transcript_text, video_id):
    """
    Splits transcript text into chunks and creates a local FAISS vector store
    using local HuggingFace embeddings. Saves the created index to disk.
    """
    # Create document object
    doc = Document(page_content=transcript_text, metadata={"source": video_id})
    
    # Split document into chunks
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    chunks = text_splitter.split_documents([doc])
    
    # Get cached embeddings
    embeddings = get_embeddings()
    
    # Store chunks in a local FAISS database
    vector_store = FAISS.from_documents(chunks, embeddings)
    
    # Cache the index to disk
    folder_path = f"faiss_indexes/index_{video_id}"
    os.makedirs(folder_path, exist_ok=True)
    vector_store.save_local(folder_path)
    
    # Save the raw transcript text file
    with open(f"{folder_path}/transcript.txt", "w", encoding="utf-8") as f:
        f.write(transcript_text)
        
    return vector_store

def get_rag_chain(vector_store, groq_api_key):
    """
    Creates the retrieval and QA chain using Groq and the FAISS vector store.
    """
    # Initialize Groq LLM
    llm = ChatGroq(
        model_name="llama-3.1-8b-instant",
        temperature=0.2,
        groq_api_key=groq_api_key
    )
    
    # Set up retriever
    retriever = vector_store.as_retriever(search_kwargs={"k": 5})
    
    # System prompt for synthesis
    system_prompt = (
        "You are a helpful and intelligent YouTube video assistant. Use the following pieces of retrieved context "
        "from the video transcript to answer the user's question.\n\n"
        "Your answers should be highly detailed, informative, and directly reference what was said in the video where possible. "
        "If the answer cannot be found in the provided context, state that it is not mentioned in the video transcript, "
        "but do not make up facts. Formulate your response in clean Markdown with paragraphs, bullet points, and bold text for readability.\n\n"
        "Context:\n{context}"
    )
    
    # Build prompt template
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("placeholder", "{chat_history}"),
        ("human", "{input}"),
    ])
    
    # Combine docs chain
    combine_docs_chain = create_stuff_documents_chain(llm, prompt)
    
    # Create retrieval chain
    retrieval_chain = create_retrieval_chain(retriever, combine_docs_chain)
    return retrieval_chain

def query_rag_engine(retrieval_chain, question, chat_history_list):
    """
    Queries the RAG chain and returns the generated answer.
    """
    # Format chat history for LangChain
    formatted_history = []
    for msg in chat_history_list:
        role = msg.get("role")
        content = msg.get("content")
        if role == "user":
            formatted_history.append(("human", content))
        elif role == "assistant":
            formatted_history.append(("assistant", content))
            
    response = retrieval_chain.invoke({
        "input": question,
        "chat_history": formatted_history
    })
    
    return response["answer"]
